# Generated by Django 4.2.7 on 2026-02-18 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='External question ID', max_length=100, unique=True)),
                ('grade', models.IntegerField(help_text='Grade level')),
                ('topic', models.CharField(help_text='Question topic/category', max_length=200)),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('true_false', 'True/False'), ('rating', 'Rating Scale')], max_length=20)),
                ('question_text', models.TextField(help_text='The question text')),
                ('options', models.JSONField(blank=True, help_text='Answer options as JSON', null=True)),
                ('correct_answer', models.CharField(help_text='Correct answer or key', max_length=200)),
                ('weight', models.FloatField(default=1.0, help_text='Question weight for scoring')),
                ('dimension', models.CharField(choices=[('aptitude', 'Aptitude'), ('logical', 'Logical Reasoning'), ('interest', 'Interest'), ('motivation', 'Motivation')], help_text='Assessment dimension', max_length=50)),
            ],
            options={
                'ordering': ['external_id'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Test name', max_length=200)),
                ('grade', models.IntegerField(help_text='Grade level for this test')),
                ('duration_minutes', models.IntegerField(help_text='Test duration in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(help_text='Question order in the test')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='assessments.question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='assessments.test')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('test', 'question')},
            },
        ),
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(related_name='tests', through='assessments.TestQuestion', to='assessments.question'),
        ),
        migrations.CreateModel(
            name='ReportParagraphMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(help_text='Assessment dimension', max_length=50)),
                ('score_range', models.CharField(help_text="Score range (e.g., '0-30', '31-60', '61-100')", max_length=50)),
                ('student_paragraph', models.TextField(help_text='Paragraph for student report')),
                ('parent_paragraph', models.TextField(help_text='Paragraph for parent report')),
            ],
            options={
                'ordering': ['dimension', 'score_range'],
                'unique_together': {('dimension', 'score_range')},
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(blank=True, help_text='Student grade level', null=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('parent', 'Parent'), ('admin', 'Admin')], default='student', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_answers', models.JSONField(default=dict, help_text='Student answers as JSON')),
                ('scores', models.JSONField(default=dict, help_text='Computed scores by dimension')),
                ('total_score', models.FloatField(blank=True, help_text='Overall score', null=True)),
                ('pdf_report_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
